version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: socialnetwork
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    command: ["sh", "-c", "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 socialnetwork.wsgi:application"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
